### ISSUE TITLE
keep getting prompted for root password when running `fab bootstrap`

### ISSUE THREAD

**Issue by zevaverbach** [makaimc/fsp-deployment-guide#1]

**Comment by zevaverbach** [comment]
duh, it's because we already locked down root logins.  @makaimc, i'll leave you to close this, because the instruction to do `fab bootstrap` on page 57 seems to assume the previous manual steps have not already been taken.  or at least that root login has not been set to `no`.

**Comment by mattmakai** [comment]
ok :+1:. everything else going well so far?

**Comment by mattmakai** [comment]
i'll make clarification in the next update I release @zevav. thank you for the feedback, keep it coming!

**Comment by zevaverbach** [comment]
yep!  one dead link, though, FYI:
https://davidwinter.me/articles/2013/11/23/introduction-to-ansible/

Zev Averbach
Averbach Transcription
(212) 729-4850
www.avtranscription.com

**Comment by mattmakai** [comment]
darn dead links. ok, I fixed that up in fullstackpython.com as well, thank you!
