### ISSUE TITLE
Can't get playbook to work

### ISSUE THREAD

**Issue by jumpingDolphin** [makaimc/fsp-deployment-guide#15]
Hi Matt,

If I run the playbook the first time I get:

```
simon@simon-VirtualBox:~/repos/deployment/fsp-deployment-guide$ ./deploy_prod.sh 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [apply common configuration to server] ************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

./deploy_prod.sh: line 3: ./ssh_keys/prod_key: No such file or directory
```

I realized that when doing the fab bootstrap from the previous chapter, the keys are stored in files named 
myip_prod_key 
and 
myip_prod_key.pub 

So I changed the deploy_prod.sh line 3 from
./ssh_keys/prod_key -K -u deployer -i ./prod/hosts

to

./ssh_keys/myIP_prod_key -K -u deployer -i ./prod/hosts

Then I get the error

 ```
simon@simon-VirtualBox:~/repos/deployment/fsp-deployment-guide$

 ./deploy_prod.sh 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [apply common configuration to server] ************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

./ssh_keys/myip_prod_key: line 1: -----BEGIN: command not found
./ssh_keys/myip_prod_key: line 2: MIIEpAIBAAKCAQEApIpm/CRgZ06442ry3lCxQuk5S21vGhiBDphMN1EJWshk53mu: No such file or directory
./ssh_keys/myip_prod_key: line 3: SB2I/184kd9v3aUoparG9SxPGnAOWEd5YL8/Uc1ZDPVSmcNtXG50KcCqTqTaX3xV: No such file or directory 

```

I checked everything 2 and 3 times. Host file is as specified on the place specified. Do you have any Idea what the reason could be?

**Comment by 37moves** [comment]
I now have cloned your entire rep for this chapter. After setting up all again I get the following message

```
(fspdeploy) simon@simon-VirtualBox:~/repos/deployment/fspchap3$ ./deploy_prod.sh 
SUDO password: 

PLAY [apply common configuration to server] *********************************** 

GATHERING FACTS *************************************************************** 
ok: [MYIP]

TASK: [common | apt update_cache=yes] ***************************************** 
fatal: [MYIP] => Incorrect become password

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/simon/deploy.retry

MYIP            : ok=1    changed=0    unreachable=1    failed=0   

```
where MYIP is my ip. 

My guess would be that somehow the securing of the server through the key and not root gets a problem with ansible. I will continue the other chapters in the meantime.

BTW the SSL cert section could now be updated with let's encrypt ;-)

Cheers,

Simon

**Comment by mattmakai** [comment]
hey @simonschenker, looks like you need to enter the remote sudo password (on the deployer user) to run the commands as root. it's not the root password, but the password on the deployer user. kinda confusing.

totally agree about let's encrypt! wasn't available when I first wrote the book but I use it for all my projects now and will use it in the next update

**Comment by 37moves** [comment]
Thanks Matt for the quick response as always.

I don't think that this is the reason as I use the same pws for both and the first part of the script is executed. 

I continued anyway and will probably come back later to try again.
