### ISSUE TITLE
`sudo: yes`s in `ubuntu.yml` here are not reflected in book

### ISSUE THREAD

**Issue by zevaverbach** [makaimc/fsp-deployment-guide#3]

**Comment by zevaverbach** [comment]
page 56-57 @makaimc

**Comment by jkokenge** [comment]
Yeah, I'm here to report this as well.

**Comment by mattmakai** [comment]
thank you @jkokenge, this will be reflected in the next book update I send out to everyone who purchased it. will update this issue ticket when it's released

**Comment by mattmakai** [comment]
This is fixed in the December update of the book. Please re-download via Gumroad to grab the updated copy.
